### ISSUE TITLE
`FileNotFoundError` when running the latest image from docker hub

### ISSUE THREAD

**Issue by oscnord** [gdavila/easyVmaf#19] opened 2022-02-23 15:15 UTC
I'm getting a `FileNotFoundError` with the latest docker image available on docker hub when doing measurements on custom video files. Permissions have been set so that it is possible to read/write to the folder containing the video files. This however works fine with the 1.2 version of easyVmaf. 

```bash
Killed    4 fps=3.4 q=-0.0 size=N/A time=00:00:00.16 bitrate=N/A speed=0.135x     
Traceback (most recent call last):
  File "easyVmaf.py", line 150, in <module>
    with open(vmafpath) as jsonFile:
FileNotFoundError: [Errno 2] No such file or directory: '/<custom-name-folder>/distorted_vmaf.json'
```

**Comment by gdavila** [comment] 2022-02-23 15:33
May I ask you to copy/paste the cmd you are using.

**Comment by oscnord** [comment] 2022-02-23 15:38
> May I ask you to copy/paste the cmd you are using.

Of course, I'm using the one that is provided in the readme. 

```bash 
docker run --rm -v <absolute-path-to-folder>:/<custom-name-folder> gfdavila/easyvmaf -r /<custom-name-folder>/video-1.mp4 -d /<custom-name-folder>/video-2.mp4
```

**Comment by gdavila** [comment] 2022-02-23 17:39
Are you using exactly  that command line? I'm not being able to reproduce the issue.

I've tried:
 `<absolute-path-to-folder>`  = `~/Movies` -> this is my local folder
 `/<custom-name-folder>`  = `/v` -> this is how my local folder will be mounted into docker.
 
 
`docker run --rm -v ~/Movies:/v gfdavila/easyvmaf -r /v/bbb_60fps.mp4 -d /v/bbb_60fps.mp4`

Also, what OS are you using?

**Comment by oscnord** [comment] 2022-02-23 19:12
Yes, I jus replaced my local paths with `<absolute-path-to-folder>` and `<custom-name-folder>` when posting it here.

```bash
docker run --rm -v /Users/oscarnord/Documents/video-files/:/video_samples gfdavila/easyvmaf -r /video_samples/video-1.mp4 -d /video_samples/video-2.mp4
```

I'm on MacOS `12.2.1 (21D62)`

**Comment by gdavila** [comment] 2022-02-23 19:58
Thanks. I still can't reproduce the issue on my end what makes me believe that this could be related with the content + the vmaf update. May I ask you to upload the sample videos you are testing with? Or some content that allows me to reproduce de issue?

The following message calls my attention:
`Killed    4 fps=3.4 q=-0.0 size=N/A time=00:00:00.16 bitrate=N/A speed=0.135x `

it seems that Fmpeg ended badly.

**Comment by oscnord** [comment] 2022-02-23 20:12
> Thanks. I still can't reproduce the issue on my end what makes me believe that this could be related with the content + the Ffmpeg update. May I ask you to upload the sample videos you are testing with? Or some content that allows me to reproduce de issue?
> 
> The following message calls my attention: `Killed 4 fps=3.4 q=-0.0 size=N/A time=00:00:00.16 bitrate=N/A speed=0.135x `
> 
> it seems that Fmpeg ended badly.

This is without the FFmpeg update and with 8-bit content. I'll do some more testing on my end and see if I can upload some test content. Feels like it's something odd going on on my end as you say.

**Comment by gdavila** [comment] 2022-02-23 21:34
My mistake, I meant it seems an issue with the `content `and the `VMAF update` on the docker file - as the latest docker version has the last VMAF commit.

**Comment by gdavila** [comment] 2022-03-03 20:24
Hi @oscnord,

Where you able to reproduce the issue with some content that you can share? 

To summarize what I mentioned previously, the last Docker Image has a newer VMAF version so I strongly suspect that the issue is related booth with this VMAF update and with the content you are testing - as I was not able to reproduce the issue on my side.

**Comment by gdavila** [comment] 2022-04-16 17:45
Closing this issue as I'm not able to reproduce the issue. 
 
 I strongly suspects that the `FileNotFoundError` message  is hidden a video or file related error. Feel free to re-open it if you can share a sample file to reproduce the issue on my end.

**Closed as completed by gdavila** 2022-04-16 17:45 UTC
