### ISSUE TITLE
Progress status not updating quickly with -progress flag

### ISSUE THREAD

**Issue by Snelso91** [gdavila/easyVmaf#15] opened 2022-01-27 21:17 UTC
When using the -progress flag from the new release, the displayed progress updates appear very slowly/sporadically rather than line by line as you would normal expect.

For example, when running the docker image from the windows command line, the progress lines were only updated on the command line when the VMAF analysis reached 17%, 37%, 57%, 76% and 96%.
In-between these update points, nothing was outputted to the command line and then when the update happened all of the missing progress lines since the last update were sent to the terminal in one go.

Cmd log file attached [here](https://github.com/gdavila/easyVmaf/files/7953841/easyVmaf.-progress.not.updating.quickly.cmd.exe.log.txt).

**Comment by gdavila** [comment] 2022-01-28 14:46
Thanks for reporting this. I already had noticed the same behavior when using docker however I haven't been able to find out the root cause yet.

**Comment by gdavila** [comment] 2022-05-22 03:23
Solved. 

If you run the latest docker image ([v1.3](https://hub.docker.com/layers/gfdavila/easyvmaf/latest/images/sha256-87b626971a37087201e20ad38ca63627e21c3c240c56bd8e9171c81df995914f?context=explore)). This should be fixed.

**Closed as completed by gdavila** 2022-05-22 03:23 UTC
Labels: enhancement, help wanted
