### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wisewtf** [gdavila/easyVmaf#22] opened 2022-05-21 06:43 UTC
Hello,

For some weird reason I'm getting a `FileNotFoundError: [Errno 2] No such file or directory: '/a/distorted_vmaf.xml'` error when launching the Docker image.

I was able to use it before, I have no idea what changed. It's like the scripts aren't able to create the VMAF output on their own. Are they supposed to? The same happens using JSON output.

Here's my cmdline:

`docker run --privileged --rm -v $PWD:/a/ gfdavila/easyvmaf -r /a/untouched.mkv -d /a/distorted.mkv -threads 12 -output_fmt xml`

And here's the traceback:

```
Traceback (most recent call last):
  File "easyVmaf.py", line 156, in <module>
    tree = ET.parse(vmafpath)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/a/distorted_vmaf.xml'
```

What am I doing wrong?

**Comment by gdavila** [comment] 2022-05-21 18:25
Cold you let me know what docker image version are you using?

`docker image inspect gfdavila/easyvmaf | grep Id `

Also, what do you see before the error?  I wonder specifically if ffmpeg is finishing gracefully.  Usually, you should see something like:

```
......
 frame=  571 fps= 26 q=-0.0 size=N/A time=00:00:10.03 bitrate=N/A speed=0.468x  
 frame= 3574 fps= 28 q=-0.0 Lsize=N/A time=00:01:00.08 bitrate=N/A speed=0.468x    
video:1871kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[libvmaf @ 0x560c44422740] VMAF score: 98.710106
```

I'm not being able to reproduce the issue. I tried with the 1.2 version tag and with the latest one.

**Comment by gdavila** [comment] 2023-05-11 19:17
closing this ticket As the issue is not reproducible

**Closed as not planned** 2023-05-11 19:18 UTC
